# Generated by Django 4.2.9 on 2024-05-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('scifi', 'Sci-Fi'), ('biography', 'Biography'), ('selfhelp', 'Self Help')], default='fiction', max_length=20),
        ),
    ]
