# Generated by Django 4.2.9 on 2024-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_userreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Sci-Fi', 'Sci-Fi'), ('Biography', 'Biography'), ('Self Help', 'Self Help')], default='Fiction', max_length=20),
        ),
    ]
